version: "3.9"
services:
  check:
    container_name: "check"
    image: "docker.io/janderland/fdbq-build:latest"
    command: ["/bin/sh", "-c", "./scripts/cluster.sh fdb && ./scripts/check.sh"]
    depends_on:
      - "fdb"
    working_dir: "/fdbq"
    volumes:
      - ".:/fdbq"
  fdb:
    container_name: fdb
    image: "foundationdb/foundationdb:6.3.15"
    ports:
      - "4500:4500"

