version: "3.9"
services:
  verify:
    container_name: "verify"
    image: "docker.io/janderland/fdbq-build:latest"
    depends_on:
      - "fdb"
    working_dir: "/fdbq"
    volumes:
      - ".:/fdbq"
    command:
      - "/bin/sh"
      - "-c"
      - "${COMMAND}"
  fdb:
    container_name: "fdb"
    image: "foundationdb/foundationdb:6.2.30"
    ports:
      - "4500:4500"
volumes:
  cache:
