version: "3.9"
services:
  build:
    container_name: "build"
    image: "docker.io/janderland/fdbq-build:latest"
    depends_on:
      - "fdb"
    working_dir: "/fdbq"
    volumes:
      - ".:/fdbq"
      - "cache:/cache"
  fdb:
    container_name: fdb
    image: "foundationdb/foundationdb:6.3.15"
    ports:
      - "4500:4500"
volumes:
  cache:
