on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/build
          tags: janderland/fdbq-build:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Fix
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-fdbq:
    needs: build-environment
    runs-on: ubuntu-latest
    container: janderland/fdbq-build:${{ github.sha }}
    services:
      fdb:
        image: foundationdb/foundationdb:6.3.12
        ports:
          - 4500:4500
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}
        restore-keys: go-

    - name: DB
      run: |
        FDB_IP=$(getent hosts fdb | awk '{print $1}')
        echo "docker:docker@${FDB_IP}:4500" > /etc/foundationdb/fdb.cluster
        fdbcli --exec "configure new single memory"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
