on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/build
        tags: docker.pkg.github.com/janderland/fdbq/build:${{ github.sha }}
        push: true

  build-fdbq:
    needs: build-environment
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/janderland/fdbq/build:${{ github.sha }}
    services:
      fdb:
        image: foundationdb/foundationdb:6.3.12
        ports:
          - 4500:4500
    steps:
    - name: Checkout
      uses: actions/checkout@v2  

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}
        restore-keys: go-

    - name: DB
      run: |
        FDB_IP=$(getent hosts fdb | awk '{print $1}')
        echo "docker:docker@${FDB_IP}:4500" > /etc/foundationdb/fdb.cluster
        fdbcli --exec "configure new single memory"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
