on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  FDB_URL: https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-clients_6.3.12-1_amd64.deb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: |
        wget -O fdb.deb $FDB_URL
        sudo dpkg -i ./fdb.deb
    - run: go build -v ./...
    - run: go test -v ./...
