on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  FDB_CLIENT_URL: https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-clients_6.3.12-1_amd64.deb
  FDB_SERVER_URL: https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-server_6.3.12-1_amd64.deb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: |
        wget -O -nv fdb_client.deb $FDB_CLIENT_URL
        wget -O -nv fdb_server.deb $FDB_SERVER_URL
        sudo dpkg -i ./fdb_client.deb -i ./fdb_server.deb
        fdbcli --exec "configure new single memory
    - run: go build -v ./...
    - run: go test -v ./...
