on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  FDB_CLIENT_URL: https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-clients_6.3.12-1_amd64.deb

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      fdb:
        image: foundationdb/foundationdb:latest
    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: |
        wget -qO fdb_client.deb $FDB_CLIENT_URL
        sudo dpkg -i ./fdb_client.deb
        echo "docker:docker@127.0.0.1:4500" > ./fdb.cluster
        fdbcli --exec "configure new single memory"
    - run: go build -v ./...
    - run: go test -v ./...
