on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  FDB_LIB_URL: https://www.foundationdb.org/downloads/6.3.12/ubuntu/installers/foundationdb-clients_6.3.12-1_amd64.deb

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      fdb:
        image: foundationdb/foundationdb:6.3.12
        ports:
          - 4500:4500
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2  

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install FDB client library
      run: |
        wget -qO fdb.deb $FDB_LIB_URL
        sudo dpkg -i ./fdb.deb

    - name: Setup cluster file & configure DB
      run: |
        sudo echo "docker:docker@127.0.0.1:4500" > /etc/foundationdb/fdb.cluster
        fdbcli --exec "configure new single memory"

    - name: Build Go
      run: go build -v ./...

    - name: Test Go
      run: go test -v ./...
