name: Verify
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        fdb_ver: [6.2.30, 7.1.33]
        include:
          - fdb_ver: 6.2.30
            fdb_lib_url: https://github.com/apple/foundationdb/releases/download/6.2.30/foundationdb-clients-6.2.30-1.el7.x86_64.rpm
            fdb_docker_image: foundationdb/foundationdb:6.2.30
          - fdb_ver: 7.1.33
            fdb_lib_url: https://github.com/apple/foundationdb/releases/download/7.1.33/foundationdb-clients-7.1.33-1.el7.x86_64.rpm
            fdb_docker_image: foundationdb/foundationdb:7.1.33
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify
      run: ./build.sh --generate --verify
      env:
        FDB_VER: ${{ matrix.fdb_ver }}
        FDB_LIB_URL: ${{ matrix.fdb_lib_url }}
        FDB_DOCKER_IMAGE: ${{ matrix.fdb_docker_image }}
